export const bossNameCorrect: Record<string, string> = {
    boss_nine_tailed_fox_guild: '水狐',
    九尾狐佳岚: '水狐',
    boss_invader_director_guild: '导演',
    boss_harvester_guild_fury: '蚊子',
    boss_graboid_guild_fury: '牛虫',
    boss_minister_guild: '邓肯',
    宰相邓肯: '邓肯',
    boss_robot_knight_new_guild: '帝国骑士',
    boss_portrait_guild_43th: '画像',
    boss_admiral_guild_43th_modified: '船长',
    boss_admiral_guild_43th: '船长',
    boss_mech_guild_fury_43th: '熊猫',
    boss_fairy_guild_47th: '妖精',
    erina_guild_47th: '老骑士',
    boss_demon_guild_47th: '恶魔',
    boss_mech_guild_fury_47th: '熊猫',
    机械人埃里娜: '老骑士',
    '改良疯狂熊猫MK-三型': '熊猫',
    '恶魔首领': '恶魔',
    'boss_graboid_guild_fury_46th': '牛虫',
    'boss_harvester_guild_fury_58th': '蚊子',
    'boss_wolf_guild_58th': '哥布林',
    '狂暴沙漠牛虫': '牛虫',
};